

server:
  port: 8090
  tomcat:
    max-threads: 800
    uri-encoding: utf-8
    accesslog:
      enabled: true

spring:
    jackson.date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    datasource:
        name: qixin
        #url: jdbc:mysql://127.0.0.1:3306/qixin?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
        #username: root
        #password: 123456
        url: jdbc:mysql://119.28.232.88:3306/beidou?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
        username: root
        password: Denghua+123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      database: 0
      host: 119.28.232.88
      port: 6379
      password:

mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  mapper-locations: classpath:resources/mapping/*Mapper.xml
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dcode.qixin.model



#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 打印sql
logging:
  level:
    root: warn
    com.dcode.qixin.mapper: debug
    org.springframework.web: debug
  file: d:/log/qx.log
#  pattern:
#    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
#    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
